apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yh7vfk2tx-java-springboot
  janus-idp.io/tekton: yh7vfk2tx-java-springboot
  backstage.io/kubernetes-id: yh7vfk2tx-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: yh7vfk2tx-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
